version: 2

models:
  - name: SHOPIFY_DISCOUNT_APPLICATION
    description: "Staging model for Shopify discount applications at the order level"
    config:
      materialized: incremental

    columns:
      - name: index
        description: "Index of the discount application in the order"
        tests:
          - not_null

      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - index
